# Generated by Django 3.2.5 on 2021-09-08 23:37

import cronjob.db_fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tags', models.JSONField(default=dict)),
                ('timeout_length', models.IntegerField(default=120, null=True)),
                ('job_path', cronjob.db_fields.PythonFunctionField(max_length=100)),
                ('status', cronjob.db_fields.StatusField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100)),
                ('_args', models.CharField(default='', max_length=100)),
                ('kwargs', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_ended', models.DateTimeField(default=None)),
                ('status', models.CharField(choices=[('Started', 'Job has started.'), ('Timeout', 'No Response'), ('Success', 'Job has succeeded.'), ('Failed', 'Job has failed.')], max_length=100)),
                ('exception', models.TextField(default='')),
                ('time_interval', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronjob.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', cronjob.db_fields.StatusField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('time_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('duration_unit', models.CharField(choices=[('Minute', 'Minute'), ('Hour', 'Hour'), ('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], max_length=100)),
                ('jobs', models.ManyToManyField(to='cronjob.Job')),
            ],
        ),
    ]
