# Generated by Django 3.2.5 on 2021-09-11 02:34

import cronjob.db_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='job_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cronjob.jobgroup'),
        ),
        migrations.AlterField(
            model_name='job',
            name='_args',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_path',
            field=cronjob.db_fields.PythonFunctionField(help_text='module path followed by the function name. eg. cronjob.jobs.test_function', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='kwargs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cronjob.job'),
        ),
    ]
