# Generated by Django 3.2.5 on 2021-09-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0002_auto_20210910_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='date_ended',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
